# Generated by Django 5.2.4 on 2025-08-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApplication', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='cart_code',
        ),
    ]
